CREATE TABLE "athlete_profiles" (
	"id" serial PRIMARY KEY NOT NULL,
	"user_id" integer,
	"session_id" text NOT NULL,
	"name" text NOT NULL,
	"email" text,
	"phone" text,
	"birthdate" date,
	"gender" text,
	"bio" text,
	"school" text NOT NULL,
	"division" text NOT NULL,
	"graduation_year" integer,
	"major" text,
	"gpa" real,
	"academic_honors" text,
	"sport" text NOT NULL,
	"position" text,
	"sport_achievements" text,
	"stats" jsonb,
	"social_handles" jsonb,
	"social_connections" jsonb,
	"instagram_metrics" jsonb,
	"twitter_metrics" jsonb,
	"tiktok_metrics" jsonb,
	"last_metrics_update" timestamp,
	"profile_link_enabled" boolean DEFAULT false,
	"profile_link_id" text,
	"profile_link_theme" text DEFAULT 'default',
	"profile_link_background_color" text DEFAULT '#111111',
	"profile_link_text_color" text DEFAULT '#ffffff',
	"profile_link_accent_color" text DEFAULT '#ff4500',
	"profile_link_bio" text,
	"profile_link_photo_url" text,
	"profile_link_buttons" jsonb,
	"follower_count" integer NOT NULL,
	"average_engagement_rate" real,
	"content_quality" integer,
	"post_frequency" text,
	"content_style" text NOT NULL,
	"content_types" jsonb,
	"top_performing_content_themes" jsonb,
	"media_kit_url" text,
	"compensation_goals" text NOT NULL,
	"preferred_product_categories" jsonb,
	"previous_brand_deals" jsonb,
	"available_for_travel" boolean,
	"exclusivity_requirements" text,
	"personal_values" jsonb,
	"causes" jsonb,
	"brand_personality" jsonb,
	"availability_timeframe" text,
	"minimum_compensation" text,
	"preferences" jsonb,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "business_profiles" (
	"id" serial PRIMARY KEY NOT NULL,
	"user_id" integer,
	"session_id" text NOT NULL,
	"name" text NOT NULL,
	"email" text,
	"phone" text,
	"industry" text,
	"company_size" text,
	"founded_year" integer,
	"website" text,
	"logo_url" text,
	"product_type" text NOT NULL,
	"product_description" text,
	"product_images" jsonb,
	"pricing_tier" text,
	"audience_goals" text NOT NULL,
	"audience_demographics" jsonb,
	"primary_audience_age_range" text,
	"secondary_audience_age_range" text,
	"campaign_vibe" text NOT NULL,
	"campaign_goals" jsonb,
	"campaign_frequency" text,
	"campaign_duration" text,
	"campaign_seasonality" text,
	"campaign_timeline" text,
	"values" text NOT NULL,
	"brand_voice" text,
	"brand_colors" jsonb,
	"brand_guidelines_url" text,
	"sustainability_focus" boolean,
	"target_schools_sports" text NOT NULL,
	"preferred_sports" jsonb,
	"preferred_divisions" jsonb,
	"preferred_regions" jsonb,
	"budget" text,
	"compensation_model" text,
	"budget_per_athlete" text,
	"previous_influencer_campaigns" jsonb,
	"campaign_success_metrics" jsonb,
	"preferences" jsonb,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "campaigns" (
	"id" serial PRIMARY KEY NOT NULL,
	"business_id" integer NOT NULL,
	"title" text NOT NULL,
	"description" text NOT NULL,
	"campaign_brief" text,
	"campaign_type" text,
	"deliverables" jsonb NOT NULL,
	"content_requirements" jsonb,
	"brand_mention_requirements" text,
	"hashtag_requirements" jsonb,
	"exclusivity_clause" text,
	"start_date" date,
	"end_date" date,
	"submission_deadlines" jsonb,
	"target_audience" jsonb,
	"target_sports" jsonb,
	"target_divisions" jsonb,
	"target_regions" jsonb,
	"target_follower_counts" jsonb,
	"target_engagement_rates" jsonb,
	"budget" text,
	"compensation_details" jsonb,
	"kpis" jsonb,
	"goals" jsonb,
	"status" text DEFAULT 'draft',
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "compliance_officers" (
	"id" serial PRIMARY KEY NOT NULL,
	"user_id" integer,
	"name" text NOT NULL,
	"email" text NOT NULL,
	"institution" text NOT NULL,
	"department" text NOT NULL,
	"title" text NOT NULL,
	"permissions" jsonb,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "feedbacks" (
	"id" serial PRIMARY KEY NOT NULL,
	"user_id" integer NOT NULL,
	"user_type" text NOT NULL,
	"feedback_type" text NOT NULL,
	"match_id" integer,
	"rating" integer,
	"title" text NOT NULL,
	"content" text NOT NULL,
	"sentiment" text,
	"status" text DEFAULT 'pending' NOT NULL,
	"is_public" boolean DEFAULT false,
	"admin_response" text,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "match_scores" (
	"id" serial PRIMARY KEY NOT NULL,
	"athlete_id" integer NOT NULL,
	"business_id" integer NOT NULL,
	"campaign_id" integer NOT NULL,
	"score" real NOT NULL,
	"reason" text NOT NULL,
	"strength_areas" jsonb,
	"weakness_areas" jsonb,
	"audience_fit_score" real,
	"content_style_fit_score" real,
	"brand_value_alignment_score" real,
	"engagement_potential_score" real,
	"compensation_fit_score" real,
	"academic_alignment_score" real,
	"geographic_fit_score" real,
	"timing_compatibility_score" real,
	"platform_specialization_score" real,
	"status" text DEFAULT 'pending',
	"athlete_response" text,
	"business_response" text,
	"compliance_status" text DEFAULT 'pending',
	"compliance_officer_id" integer,
	"compliance_notes" text,
	"matched_at" timestamp DEFAULT now(),
	"responded_at" timestamp,
	"approved_at" timestamp,
	"completed_at" timestamp,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "messages" (
	"id" serial PRIMARY KEY NOT NULL,
	"session_id" text NOT NULL,
	"role" text NOT NULL,
	"content" text NOT NULL,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "partnership_offers" (
	"id" serial PRIMARY KEY NOT NULL,
	"match_id" integer NOT NULL,
	"business_id" integer NOT NULL,
	"athlete_id" integer NOT NULL,
	"campaign_id" integer NOT NULL,
	"compensation_type" text NOT NULL,
	"offer_amount" text NOT NULL,
	"payment_schedule" text,
	"bonus_structure" text,
	"deliverables" jsonb NOT NULL,
	"content_specifications" text,
	"post_frequency" text,
	"approval_process" text,
	"usage_rights" text NOT NULL,
	"term" text NOT NULL,
	"exclusivity" text,
	"geographic_restrictions" text,
	"status" text DEFAULT 'pending' NOT NULL,
	"athlete_viewed_at" timestamp,
	"athlete_responded_at" timestamp,
	"business_updated_at" timestamp,
	"compliance_status" text DEFAULT 'pending',
	"compliance_notes" text,
	"compliance_reviewed_at" timestamp,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	"expires_at" timestamp
);
--> statement-breakpoint
CREATE TABLE "sessions" (
	"id" serial PRIMARY KEY NOT NULL,
	"session_id" text NOT NULL,
	"user_type" text,
	"data" jsonb,
	"profile_completed" boolean DEFAULT false,
	"athlete_id" integer,
	"business_id" integer,
	"last_login" timestamp DEFAULT now(),
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "sessions_session_id_unique" UNIQUE("session_id")
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" serial PRIMARY KEY NOT NULL,
	"username" text NOT NULL,
	"email" text NOT NULL,
	"password" text NOT NULL,
	"user_type" text NOT NULL,
	"session_id" text,
	"verified" boolean DEFAULT false,
	"avatar" text,
	"stripe_customer_id" text,
	"stripe_subscription_id" text,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "users_username_unique" UNIQUE("username"),
	CONSTRAINT "users_email_unique" UNIQUE("email")
);
--> statement-breakpoint
ALTER TABLE "feedbacks" ADD CONSTRAINT "feedbacks_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "feedbacks" ADD CONSTRAINT "feedbacks_match_id_match_scores_id_fk" FOREIGN KEY ("match_id") REFERENCES "public"."match_scores"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "partnership_offers" ADD CONSTRAINT "partnership_offers_match_id_match_scores_id_fk" FOREIGN KEY ("match_id") REFERENCES "public"."match_scores"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "partnership_offers" ADD CONSTRAINT "partnership_offers_business_id_business_profiles_id_fk" FOREIGN KEY ("business_id") REFERENCES "public"."business_profiles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "partnership_offers" ADD CONSTRAINT "partnership_offers_athlete_id_athlete_profiles_id_fk" FOREIGN KEY ("athlete_id") REFERENCES "public"."athlete_profiles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "partnership_offers" ADD CONSTRAINT "partnership_offers_campaign_id_campaigns_id_fk" FOREIGN KEY ("campaign_id") REFERENCES "public"."campaigns"("id") ON DELETE no action ON UPDATE no action;